cookie:
  expiry_days: 30
  key: 12asd74fjxa231kdk234fsa
  name: regulation_buddy_auth
credentials:
  usernames:
    efraserhurley:
      assistant: regulations-buddy
      email: e.fraserhurley@yordasgroup.com
      failed_login_attempts: 0
      logged_in: true
      name: Eloise Fraser-Hurley
      password: $2b$12$Od9ZZ.Cs8KQxQOQQOMa.f./WXJ83nhADvIaQ/p1x9wG7YRdfa4.va
    lgraham:
      assistant: regulations-buddy
      email: l.graham@yordasgroup.com
      failed_login_attempts: 0
      logged_in: false
      name: Lee Graham
      password: $2b$12$1rlOZXNbhDZFk1ZLyyx5NOfE5EetVn9EAfZqsNg/H8B0Y6aXGH77S
    rheubner:
      assistant: regulations-buddy
      email: r.heubner@yordasgroup.com
      failed_login_attempts: 0
      logged_in: true
      name: Ross Heubner
      password: $2b$12$A2QJmJe7cfx/gop/Hc22q.wLOHI9.v./vso7/WBMzzNBuyvxBQoHG
pre-authorized:
  emails: null
